name: pitik_app_kit
description: 'A new Flutter package project.'
version: 1.0.0

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.7.0
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  extended_image: ^8.2.0
  flutter_riverpod: ^2.0.2
  flutter_masked_text2: ^0.9.1
  intl: ^0.18.0
  nil: ^1.1.1
  fluttertoast: ^8.2.4
  dropdown_button2: ^2.3.9
  loading_animation_widget: ^1.2.1
  file_picker: ^8.0.0+1
  image_picker: ^1.0.7
  getwidget: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/animations/
    - assets/svg/
    - assets/images/
  uses-material-design: true

flutter_gen:
  output: lib/src/assets/
  integrations:
    flutter_svg: true
    lottie: true
