name: pitik_app_core
description: 'A new Flutter package project.'
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  auto_route: ^7.8.4
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.0.17
  state_notifier: ^0.7.2+1
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1
  chucker_flutter: ^1.6.3
  firebase_core: ^2.27.1
  firebase_crashlytics: ^3.4.19
  firebase_messaging: ^14.7.20
  firebase_remote_config: ^4.3.18
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  http_mock_adapter: ^0.6.0
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  state_notifier_test: ^0.0.9
  test_coverage_badge: ^0.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
